# Generated by Django 3.2.13 on 2022-07-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('cv', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
