# Generated by Django 3.2.13 on 2022-07-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='user_email',
            field=models.EmailField(max_length=100),
        ),
    ]
